#nom du workflow
name: Lechemin CI workflow

#déclencheur du workflow
on:
  push:
    branches: [ main ]

#tâches
jobs:
  #nom de la tâche
  CI:
    #choix de l'OS
    runs-on: ubuntu-latest

    #etapes
    steps:
      - 
        name: Cloner le repository
        uses: actions/checkout@v6

      -
        name: Installer les dépendances
        working-directory: code
        run: npm ci 
      
      -
        name: Complier le project React
        working-directory: code
        run: npm run build