#nom du workflow
name: Lechemin CI workflows

#déclencheur du workflow
on:
  push:
    branches: [ main ]

#tâches
jobs:
  #nom de la tâche
  CI:
    #choix de l'OS
    runs-on: ubuntu-latest

    #etapes
    steps:
      - 
        name: Cloner le repository
        uses: actions/checkout@v6

      -
        name: Installer les dépendances
        working-directory: code
        run: npm ci 
      
      -
        name: Complier le project React
        working-directory: code
        run: npm run build

      -
        name: Démarrer MYSQL et importer la base de données de tests
        working-directory: code/mysql
        run: |
          mysql -uroot -proot -e "source lechemin.test.sql;"
          mysql -uroot -proot -e "source ia.test.sql;"
          mysql -uroot -proot -e "show databases;"